src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OperationRepository::class)
 */
class Operation
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=15)
     * @Assert\IdenticalTo("débit", "retrait")
     */
    private $operation_type;

    /**
     * @ORM\Column(type="float")
     * @Assert\Positive(
     *      message = "Attention ce champ ne peut être négatif"
     * )
     */
    private $operation_amount;

    /**
     * @ORM\Column(type="datetime")
     */
    private $registered;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 10,
     *      max = 50,
     *      minMessage = "L'intitulé de votre opération doit contenir au minimum {{ limit }} caractères",
     *      maxMessage = "L'intitulé de votre opération doit contenir au maximum {{ limit }} caractères"
     * )
     */
    private $label;

    /**
     * @ORM\ManyToOne(targetEntity=Account::class, inversedBy="operations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $account;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOperationType(): ?string
    {
        return $this->operation_type;
    }

    public function setOperationType(string $operation_type): self
    {
        $this->operation_type = $operation_type;

        return $this;
    }

    public function getOperationAmount(): ?float
    {
        return $this->operation_amount;
    }

    public function setOperationAmount(float $operation_amount): self
    {
        $this->operation_amount = $operation_amount;

        return $this;
    }

    public function getRegistered(): ?\DateTimeInterface
    {
        return $this->registered;
    }

    public function setRegistered(\DateTimeInterface $registered): self
    {
        $this->registered = $registered;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): self
    {
        $this->account = $account;

        return $this;
    }
}

src/Controller/BankController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;

use App\Entity\Account;
use App\Form\AccountType;
use App\Repository\AccountRepository;

use App\Entity\Operation;
use App\Form\OperationType;
use App\Repository\OperationRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @IsGranted("IS_AUTHENTICATED_FULLY")
 */
class BankController extends AbstractController
{
    //PAGE D'ACCUEIL AVEC LA LISTE DES COMPTES
    #[Route('/', name: 'accountsList')]
    public function accountsList(): Response
    {

        $accounts = $this->getUser()->getAccounts(); // gets the actualy connected user accounts list

        return $this->render('bank/accountsList.html.twig', [
            "accounts" => $accounts,
        ]);
    }
    
    //PAGE D'AFFICHAGE D'UN SEUL COMPTE
    #[Route('/account/single/{id}', name: 'singleAccount')]
    public function singleAccount(int $id, AccountRepository $accountRepository): Response
    {   
        $user = $this->getUser()->getId(); //gets the actualy connected user

        //Making sure account data being load is current User's data ans gets the selected account
        $account = $accountRepository->findOneBy(array('id' => $id, 'user' => $user));

        return $this->render('bank/singleAccount.html.twig', [
            "account" => $account
        ]);
    }
    
    //PAGE D'AJOUT D'UN NOUVEAU COMPTE
    #[Route('/account/new_account', name: 'addAccountPage')]
    public function addAccountPage(Request $request): Response
    {
        $accounts = $this->getUser()->getAccounts(); // gets the actualy connected user accounts list
        
        $account = new Account();

        $form = $this->createForm(AccountType::class, $account);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $account->setOpeningDate(new \DateTime()); //Adds the now date time to the account
            $account->setUser($this->getUser()); //Adds the connected user to the account

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($account);
            $entityManager->flush();

            return $this->redirectToRoute('accountsList');
        }
        return $this->render('bank/addAccountPage.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    //PAGE DE CLOTURE DE COMPTE
    #[Route('/account/close_account/{id}', name: 'closeAccountPage', requirements: ['id' => '\d+'])]
    public function closeAccountPage(int $id, AccountRepository $accountRepository ,Request $request): Response
    {
        $user = $this->getUser()->getId(); //gets the actualy connected user
        $account = $accountRepository->findOneBy(array('id' => $id, 'user' => $user)); // gets the actualy connected user account selected
        
        if ($account) {
            $removeRequest = $this->getDoctrine()->getManager(); //Prepare the request

            $this->addFlash(
                'success',
                "Votre compte a bien été supprimé"
            );                                                     //Adds a success message

            $removeRequest->remove($account);                   //Sets the remove methode
            $removeRequest->flush();                            //Pass the request
        }
        elseif(!$account) {
            $this->addFlash(
                'danger',
                "N'essayez pas de supprimer les comptes des autres"
            );                                                     //Adds an error message if user tries to delete another user account
        }
        return $this->redirectToRoute('accountsList');
    }

    //PAGE D'OPERATION DEPOT/RETRAIT
    #[Route('/operation/deposit_withdrawal/{accountId}/{depotRetrait}', name: 'depositWithdrawalPage', methods: ['GET', 'POST'], requirements: ['accountId' => '\d+', 'depotRetrait' => '\d+'])]
    public function depositWithdrawalPage(int $accountId ,int $depotRetrait,AccountRepository $accountRepository, Request $request): Response
    {
        $operation = new Operation();
        $user = $this->getUser()->getId(); // gets the actualy connected user
        $account = $accountRepository->findOneBy(array('id' => $accountId, 'user' => $user)); // gets the actualy connected user account selected
        
        //To make sure that form for deposit/withdrawal only get shown if it's current user's account and prevent abuse
        if ($account) {

            $soldeActuel = $account->getAmount(); //gets the actual balance of the selected account 

            if ($depotRetrait === 1) { //verify the operation type 1 means deposit
                $ope = 'crédit';   
            }
            elseif($depotRetrait === 2){ //verify the operation type 1 means withdraw
                $ope = 'débit';
            }

            $form = $this->createForm(OperationType::class, $operation);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $operation->setOperationType($ope); //Add werever it's a deposit or a withdraw 
                $operation->setRegistered(new \DateTime()); //Add now time of opetation
                $operation->setAccount($account); //Add the actual account we are working on

                //Apply operation on account balance
                if ($depotRetrait === 1) {
                    $newSolde = $soldeActuel + $operation->getOperationAmount();
                }
                elseif($depotRetrait === 2){
                    $newSolde = $soldeActuel - $operation->getOperationAmount();
                }
                
                $operation->getAccount()->setAmount($newSolde); //Update account balance

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($operation);
                $entityManager->flush();

                return $this->redirectToRoute('singleAccount', ['id' => $accountId]); // get back to the actual account page
            }

            return $this->render('bank/depositWithdrawalPage.html.twig', [
                'form' => $form->createView(),
                'account' => $account,
                'ope' => $ope,
            ]);
        }

        return $this->redirectToRoute('accountsList');
        
    }

    //PAGE D'OPERATION DE TRANSFERT ------------------------------------------ A FINIR SI LE TEMPS
    #[Route('/operation/transfer', name: 'transferPage')]
    public function transferPage(): Response
    {
        return $this->render('bank/transferPage.html.twig', [
        ]);
    }

    //PAGE DES MENTIONS LEGALES
    #[Route('/legals', name: 'legalsPage')]
    public function legalsPage(): Response
    {
        return $this->render('bank/legalsPage.html.twig', [
        ]);
    }

    //PAGE DES STATISTIQUES ------------------------------------------ A FINIR SI LE TEMPS
    #[Route('/statistics', name: 'statisticsPage')]
    public function statisticsPage(): Response
    {
        return $this->render('bank/statisticsPage.html.twig', [
        ]);
    }

    //PAGE ACTUALITES ------------------------------------------ A FINIR SI LE TEMPS
    #[Route('/blog', name: 'blogPage')]
    public function blogPage(): Response
    {
        return $this->render('bank/blogPage.html.twig', [
        ]);
    }
    
}

templates/bank/accountsList.html.twig
{% extends 'base.html.twig' %}

{% block title %}Group Bank - Vos comptes{% endblock %}

{% block body %}
    <div class="row">
            <h1 class="color-sombre col-12 mb-5">Vos comptes bancaires</h1>
            {# read and display all flash messages #}
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ label }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endfor %}
            <section class="container col-12 row mx-auto" id="accountsContainer">
                {# Loop to show all curent user's accounts #}
                {% for account in accounts %}
                <div class='col-12 col-lg-4 my-3 mx-auto'>
                    <div class='card mx-1'>
                        <div class='card-body'>
                            <h5 class='card-title'>{{ account.accountType|replace({'-': " "}) }}</h5>
                            <p class='card-text'>N° {{account.id}}</p>
                        </div>
                        <ul class='list-group list-group-flush'>
                            <li class='list-group-item owner'> Propriétaire : <strong>{{account.user.firstname ~ " " ~ account.user.lastname}}</strong></li> <!-- intégrer nom du User-->
                            <li class='list-group-item balance'> Solde : {{account.amount}} Simflouz</li>
                            <li class='list-group-item balance'> Dernière opération : <br/>  => - INTITULE D'OPERATION : </li> <!-- intégrer titre dernière opération et montant -->
                        </ul>
                        <div class='card-body text-center'>
                            <a href='{{ path('singleAccount', {id: account.id}) }}' class='btn btn-gold'>Consulter</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </section>
        </div>
{% endblock %}

templates/bank/addAccountPage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Group Bank - Nouveau compte{% endblock %}

{% block body %}
    <div class="row">
        <h1 class="color-sombre col-12 mb-5">Ouvrir un nouveau compte</h1>
        <section class="container col-10 row mx-auto" id="postContainer">
            <div class="form-group row">
                {{ form_start(form) }}
                    <div class="my-custom-class-for-errors">
                        {{ form_errors(form) }}
                    </div>

                    <div class="row">
                        <div class="col-12 mb-3">
                            {{ form_row(form.accountType) }}
                        </div>
                        <div class="col-12 mb-3" id="some-custom-id">
                            {{ form_row(form.amount) }}
                        </div>
                        <div class="col-12 mb-3">
                            {{ form_row(form.enregistrer) }}
                        </div>
                    </div>
                {{ form_end(form) }}
            </div>
        </section>
        </div>
{% endblock %}

templates/bank/blogPage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Group Bank - Actualités{% endblock %}

{% block body %}
    <div class="row">
        <h1 class="color-sombre col-12 mb-5">Actualités de Group Bank</h1>
        <section class="container col-10 row mx-auto" id="postContainer">
            <!-- contenu du blog-->
        </section>
        </div>
{% endblock %}

templates/bank/depositWithdrawalPage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Group Bank - Dêpot - Retrait {% endblock %}

{% block body %}
    <div class="row">
        <h1 class="color-sombre col-12 mb-5">Effectuer un {{ ope }} sur {{account.accountType}}</h1>
        <section class="container col-10 row mx-auto" id="postContainer">
            <div class="form-group row">
                {{ form_start(form) }}
                    <div class="my-custom-class-for-errors">
                        {{ form_errors(form) }}
                    </div>
                    <div class="row">
                        <div class="col-12 mb-3" id="some-custom-id">
                            {{ form_row(form.label) }}
                        </div>
                        <div class="col-12 mb-3" id="some-custom-id">
                            {{ form_row(form.operation_amount) }}
                        </div>
                        <div class="col-12 mb-3">
                            {{ form_row(form.enregistrer) }}
                        </div>
                    </div>
                {{ form_end(form) }} 
            </div>
        </section>
        </div>
{% endblock %}

templates/bank/legalsPage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Group Bank - Mentions légales{% endblock %}

{% block body %}
    <div class="row">
            <h1 class="color-sombre mb-5">Mentions Légales</h1>
            <section class="container col-12">
                <div class="row">
                    <article>
                        <h2>Création</h2>
                        <p>La banque Group Bank est un immense édifice à la façade aussi blanche que la neige qui domine les boutiques alentour. Le bâtiment est doté d'un portail monumental en bronze, gardé par un gobelin en uniforme, et auquel on accède par un escalier de marbre blanc. L'entrée principale donne accès au sas, où deux bandis sont postés de chaque côté de grandes portes en argent, sur lesquelles est gravé un poème en guise d'avertissement.[3]</p>
                    </article>
                    <article>
                        <h2>Généralités</h2>
                        <p>Après avoir franchi les portes du sas, le visiteur pénètre à l'intérieur d'un vaste hall, tout en marbre. On retrouve dans cette salle un long comptoir où travaille près d'une centaine de guichetiers peut souriants assis sur de hauts tabourets.[3]</p>
                    </article>
                    <article>
                        <h2>Localisation et accès</h2>
                        <p>Une des portes du hall mène à un couloir de pierre brute, éclairé par plusieurs torches. Ce couloir permet d'accéder à des wagons.[5]</p>
                    </article>
                    <article>
                        <h2>Description</h2>
                        <p>Sous le hall principal s'étend un vaste dédale de galeries souterraines, longues de plusieurs kilomètres et accessibles par les petits wagonnets. Ces derniers s'enfoncent à vive allure dans les profondeurs de la banque et leur vitesse n'est pas modifiable.[3] Un lac souterrain est également présent parmi les galeries.[5]</p>
                    </article>
                    <article>
                        <h2>Sécurité et protections</h2>
                        <p>Le hall de la banque est constitué d'une longue allée bordée de plusieurs comptoirs où travaillent des guichetiers caféïnés. Au fond de cette allée se trouve un comptoir individuel où travail le boss des inerneters. D'imposants lustres surplombent la salle et le sol est en marbre avec diverses formes géométriques et une étoile gravée. Les bureaux des guichetiers accros au Calvados possèdent tous des balances et sont équipés d'une lampe sphérique.[4]</p>
                    </article>
                    <article>
                        <h2>Chambres fortes</h2>
                        <p>Un important dédale souterrain est présent sous la banque. Cette immense grotte est aménagée avec des rails pour que des wagons puissent s'aventurer dans les profondeurs des galeries. Les coffres de la banque sont préservés dans ces souterrains. Certains coffres sont particulièrement bien protégés et profondément enfouis dans le sous-sol. Ils sont disposés en arc de cercle sur plusieurs étages, des colonnes de pierre encerclent une tapette géante qui protège les lieux.[6]</p>
                    </article>
                </div>
            </section>
        </div>
{% endblock %}

templates/bank/singleAccount.html.twig
{% extends 'base.html.twig' %}
{# Changing Title with account number (only if account id is correct) #}
{% block title %}Group Bank - Votre {% if account is not empty %}{{ account.accountType|replace({'-': " "}) }}{% endif %}{% endblock %}

{% block body %}
    {# To make sure that {{account}} is not empty to avoid a fatal error if User type an account ID that is not his #}
    {% if account is not empty %}
        <div class="row">
            <article class="container col-12 row mx-auto" id="accountContainer">
                <div class="col-12 mx-auto">
                    <div class="card mx-1">
                        <div class="row card-body justify-content-center align-items-center text-center bg-sombre">
                            <div class="col-sm-4 vh-2">
                                <img class="img-fluid" src="{{ asset('img/gg-key.png') }}" alt="Key to Group bank">
                            </div>
                            <div class="row col-sm-8 align-items-center">
                                <div class="col-sm-6">
                                    <h1 class="card-title color-gold m-0">{{ account.accountType|replace({'-': " "}) }}</h1>
                                </div>
                                <div class="col-sm-6">
                                    <p class="card-text m-0 text-white">N° {{account.id}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <ul class="list-group list-group-flush borderGold">
                        <li class="list-group-item owner">Date de création : {{account.openingdate|date('d/m/Y')}}</li>
                        <li class="list-group-item owner borderGrey">Solde : {{account.amount}} Simflouz</li>
                        <h3 class="text-center my-3">Opérations</h3>
                            {% if account.operations is not empty %}
                                {% for operation in account.operations %}
                                <li class="list-group-item balance"> 
                                    {# To show with colors what type of operation it is (credit or debit) #}
                                    {% if operation.operationType is same as "débit" %}
                                        <strong class="text-danger">{{operation.operationType|capitalize}}</strong>
                                    {% else %} 
                                        <strong class="text-success">{{operation.operationType|capitalize}}</strong>
                                    {% endif %}
                                    ===> Le {{operation.registered|date('d/m/Y')}} à {{operation.registered|date('H:i')}} : {{operation.label}} = {{operation.operationamount}} SF
                                </li>
                                {% endfor %}
                            {% endif %}
                    </ul>
                    <div class="card-body text-center bg-sombre">
                        <a href="{{ path("closeAccountPage", {id: account.id}) }}" class="btn btn-gold mx-1">Clore</a>
                        <a href="{{ path("depositWithdrawalPage", {accountId: account.id, depotRetrait: 1} ) }}" class="btn btn-gold mx-1">Dépôt</a>
                        <a href="{{ path("depositWithdrawalPage", {accountId: account.id, depotRetrait: 2} ) }}" class="btn btn-gold mx-1">Retrait</a>
                    </div>
                </div>
            </article>
        </div>
    {# If account is empty (meaning id in URL does not go to current user's account) #}
    {% else %}
        <div class="alert alert-danger">
            <p>Vous tentez d'accéder à un compte ne vous appartenant pas.<br>Les autorités viennent d'être alertés<br>Restez où vous êtes</p>
        </div>
    {% endif %}
{% endblock %}

templates/bank/statisticsPage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Group Bank - Statistiques{% endblock %}

{% block body %}
    <div class="row">
            <h1 class="color-sombre col-12 mb-5">Voici les informations pratiques fournies par Group GBank</h1>
            <section class="container col-10 row mx-auto">
                <table class="table table-sombre table-striped text-center">
                    <thead>
                        <tr>
                            <th scope="col">Monnaie</th>
                            <th scope="col">Unité</th>
                            <th scope="col">Taux</th>
                        </tr>
                    </thead>
                    <tbody id="statsContainer">
                        <!-- inserer les données des statistiques -->
                    </tbody>
                </table>
            </section>
        </div>
{% endblock %}

templates/bank/transferPage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Group Bank - Transfert{% endblock %}

{% block body %}
    <div class="row">
        <h1 class="color-sombre col-12 mb-5">Effectuer un transfert entre NOMDUPEMIERCOMPTE et NOMDUSECONDCOMPTE</h1> {# inserer noms des comptes ??? #}
        <section class="container col-10 row mx-auto" id="postContainer">
            <!-- inserer formulaire de transfert-->
        </section>
        </div>
{% endblock %}